book_shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from post.views import *
from yonghu.views import *
from backmanage.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', index, name='index'),
    url(r'^user/', include('yonghu.urls', namespace='yonghu')),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^transfer/$', login_required_transfer),
    url(r'^buy/', include('buy.urls', namespace='buy')),
    url(r'^manage/', include('backmanage.urls', namespace='manage')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buy/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
				url(r'^buycar/(?P<post_id>[0-9]+)/$', add_to_buycar, name="add_to_buycar"),
				url(r'^buycar/show/$', show_buycar, name="show_buycar"),
				url(r'^order/add/$', add_order, name="add_order"),
				url(r'^order/user_order/$', user_order, name='user_order'),
				url(r'^order/(?P<order_id>[0-9]+)/$', order, name='order'),
				url(r'^item/confirm/(?P<item_id>[0-9]+)/$', item_confirm, name="item_confirm"),
				url(r'^item/send/(?P<item_id>[0-9]+)/$', item_send, name="item_send"),
				url(r'^item/receive/(?P<item_id>[0-9]+)/$', item_receive, name="item_receive"),
			]

post/urls.py
from django.conf.urls import url
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^write/', write, name='write'),
	url(r'^post/(?P<post_id>[0-9]+)/$', posts, name='post'),
	url(r'^userpost/(?P<user_id>[0-9]+)/$', user_post, name='user_post'),
	url(r'^usercomment/(?P<user_id>[0-9]+)/$', user_comment, name='user_comment'),
	url(r'category/(?P<cate_id>[0-9]+)/$', category, name='category'),
]

yonghu/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^profile/(?P<user_id>[0-9]+)/$', profile, name="profile"),
	url(r'^login/', login, name='login'),
	url(r'^logout/', logout, name='logout'),
]

yonghu/models.py
import random
from django.db import models
from django.contrib.auth.models import User

# 用户的资料
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	nickname = models.CharField(max_length=10, blank=True)
	age = models.IntegerField(null=True, blank=True)
	is_boy = models.NullBooleanField(null=True, blank=True)
	note = models.TextField(null=True, blank=True)
	head_cut = models.ImageField(default='/media/head_cuts/default.jpg' ,upload_to='head_cuts')
	
	def __str__(self):
		return self.user.username

# 增加测试用户
def add_robot(x,y):
	for i in range(x,y):
		name = 'robot%s' %i
		robot = User(username=name, password='cat', is_active=1)
		robot.save()
		robot_profile = Profile(user=robot,nickname=robot.username)
		robot_profile.save()
		print(robot)

yonghu/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['nickname', 'age', 'is_boy', 'note', 'head_cut']

	def __init__(self, *args, **kw):
		super(ProfileForm, self).__init__(*args, **kw)

		self.fields['nickname'].label = '昵称'
		self.fields['age'].label = '年龄'
		self.fields['is_boy'].label = '是男生吗'
		self.fields['note'].label = '个人宣言'
		self.fields['head_cut'].label = '请上传头像(尺寸50*50为佳)'

yonghu/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import auth, messages
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from . import forms, models
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.


def login(request):
	if request.method == "POST":
		user = authenticate(username=request.POST['username'],\
							password=request.POST['password'])
		if user is not None:
			if user.is_active:
				username = user.username
				auth.login(request, user)
				messages.info(request, '登录成功！')
				# 登录时判断用户是否有资料模型，没有则创建一个
				has_p = models.Profile.objects.filter(user=user).first()
				if has_p is None:
					cre_p = models.Profile(user=user,nickname=user.username)
					cre_p.save()
				return redirect('/')
			else:
				messages.info(request, '账号未激活，请去邮箱激活...')
		else:
			messages.warning(request, '账号不存在，或用户名/密码错误...')

	return render(request, 'yonghu/login.html')

@login_required(login_url='/transfer/')
def logout(request):
	auth.logout(request)
	messages.info(request, "成功注销...")
	return redirect('/')


# @login_required(login_url="/transfer/")
def profile(request, user_id):
	'''
		展示用户资料，关注取关用户，以及修改用户资料
	'''
	profile_user = get_object_or_404(User, pk=user_id)			# 拿到当前页面的用户对象

	try:
		profile = models.Profile.objects.get(user=profile_user)
	except:
		profile = models.Profile(user=profile_user)
	if request.user.is_authenticated():
		username = request.user.username
		user = User.objects.get(username=username)	# 拿到数据库中的当前用户对象
		is_mine_profile = user == profile_user
		if request.method == 'POST':
			# 只有当前用户等于登录用户时模板才显示修改表单
			old_nickname = user.profile.nickname
			if request.POST['nickname'] == '':
				request.POST['nickname'] = user.profile.nickname
			profile_form = forms.ProfileForm(request.POST, instance=profile)
			if profile_form.is_valid():
				profile_form.save()
				profile.head_cut = request.FILES.get('head_cut')						# 不知为何用ModelForm保存文件没用
				if profile.head_cut != None:
					profile.save()
			messages.info(request, '个人资料已储存')
			return redirect('yonghu:profile', user_id=user.id)
			# else:
			# 	messages.info(request, '资料全都要填')
		else:
			profile_form = forms.ProfileForm()
	messages.get_messages(request)

	return render(request, 'yonghu/profile.html', locals())


# login_required提示页面
def login_required_transfer(request):
	return render(request, 'yonghu/login_required_transfer.html')

yonghu/templates/yonghu/login.html
{% extends "base.html" %}
{% block title %}Zblog - 登录{% endblock %}

{% block content %}

<div class="row clearfix">
	<div class="col-md-12 column">
		<h3>还没有账号？点击<a href="/accounts/register"><i>这里</i></a>去注册吧...</h3>
		<br><br>
		<form role="form" action="." method="POST">
			{% csrf_token %}
			<div class="form-group">
				 <label for="exampleInputuser">账  号</label>
				 <input type="text" name="username" class="form-control" id="exampleInputuser" />
			</div>
			<div class="form-group">
				 <label for="exampleInputPassword1">密  码</label>
				 <input type="password" name="password" class="form-control" id="exampleInputPassword1" />
			</div>
			 <button type="submit" class="btn btn-default">登录</button>
		</form>
	</div>
</div>
{% endblock %}

yonghu/templates/yonghu/login_required_transfer.html
{% extends "base.html" %}
{% block title %}Zblog - 登录{% endblock %}

{% block content %}
 
<h3>你访问的页面需要登录才能使用,<span id="time">5</span>秒钟自动跳到首页</h3>
<script type="text/javascript">
	$(function () {
      setTimeout(ChangeTime, 1000);
    });
    function ChangeTime() {
      var time;
      time = $("#time").text();    
      time = parseInt(time);
      time--;
      if (time <= 0) {
        window.location.href = "{% url 'index' %}";
      } else {
        $("#time").text(time);
        setTimeout(ChangeTime, 1000);
      }
    }
</script>
{% endblock %}

yonghu/templates/yonghu/profile.html
{% extends "base.html" %}
{% block title %}Zblog - 资料{% endblock %}

{% block content %}

<div class="row clearfix">
	<div class="col-md-12 column">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">
					{{ profile.user.username }}
				</h3>
			</div>
			<div class="panel-body head-cut">
				头像: <img class="img-thumbnail" src="{{ profile.head_cut.url }}" />&nbsp;&nbsp;&nbsp;&nbsp;
				
				<br>
				昵称: {{ profile.nickname }}<br>
				年龄: {{ profile.age | default:'芳龄未知' }}<br>
				性别: {% if profile.is_boy %}男{% else %}女{% endif %} <br>
				个人宣言: {{ profile.note | default:'什么都没写，他想要平静的生活...' }}<br>
			 	
				<p><a href="{% url 'post:user_post' profile.user.id %}">他发布过的商品>>></a></p>
				<p><a href="{% url 'post:user_comment' profile.user.id %}">他发布过的评论>>></a></p>

			</div>
			<!-- <div class="panel-footer">
				Panel footer
			</div> -->
		</div>
		{% if is_mine_profile %}
		<form role="form" action="." method="POST" enctype='multipart/form-data'>
			{% csrf_token %}
			<div class="form-group">
				{{ profile_form.as_p }}
			</div>
			<button type="submit" class="btn btn-default">提交</button>
		</form>
		{% endif %}
	</div>
</div>

{% endblock %}