book_shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from post.views import *
from yonghu.views import *
from backmanage.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', index, name='index'),
    url(r'^user/', include('yonghu.urls', namespace='yonghu')),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^transfer/$', login_required_transfer),
    url(r'^buy/', include('buy.urls', namespace='buy')),
    url(r'^manage/', include('backmanage.urls', namespace='manage')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buy/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
				url(r'^buycar/(?P<post_id>[0-9]+)/$', add_to_buycar, name="add_to_buycar"),
				url(r'^buycar/show/$', show_buycar, name="show_buycar"),
				url(r'^order/add/$', add_order, name="add_order"),
				url(r'^order/user_order/$', user_order, name='user_order'),
				url(r'^order/(?P<order_id>[0-9]+)/$', order, name='order'),
				url(r'^item/confirm/(?P<item_id>[0-9]+)/$', item_confirm, name="item_confirm"),
				url(r'^item/send/(?P<item_id>[0-9]+)/$', item_send, name="item_send"),
				url(r'^item/receive/(?P<item_id>[0-9]+)/$', item_receive, name="item_receive"),
			]

post/urls.py
from django.conf.urls import url
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^write/', write, name='write'),
	url(r'^post/(?P<post_id>[0-9]+)/$', posts, name='post'),
	url(r'^userpost/(?P<user_id>[0-9]+)/$', user_post, name='user_post'),
	url(r'^usercomment/(?P<user_id>[0-9]+)/$', user_comment, name='user_comment'),
	url(r'category/(?P<cate_id>[0-9]+)/$', category, name='category'),
]

yonghu/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^profile/(?P<user_id>[0-9]+)/$', profile, name="profile"),
	url(r'^login/', login, name='login'),
	url(r'^logout/', logout, name='logout'),
]

post/models.py
import random
from .generate_post_comment import post_generator, comment_generator
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
	name = models.CharField(max_length=10)

	def __str__(self):
		return self.name

class Post(models.Model):
	user = models.ForeignKey(User, on_delete=None)
	category = models.ForeignKey(Category)
	title = models.CharField(max_length=100)
	body = models.TextField()
	price = models.FloatField()
	origin_price = models.FloatField()
	photo1 = models.ImageField(null=True, blank=True, upload_to='photo/%Y/%m/%d')
	photo2 = models.ImageField(null=True, blank=True, upload_to='photo/%Y/%m/%d')
	pub_date = models.DateTimeField(auto_now_add=True)
	view_times = models.IntegerField(default=1)

	def __str__(self):
		return self.title


class Comment(models.Model):
	user = models.ForeignKey(User)
	post = models.ForeignKey(Post)
	body = models.CharField(max_length=100)
	pub_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "用户:{0}对文章{1}的评论".format(self.user.username, self.post.title)

def add_post(x):
	user_len = User.objects.all().count()
	for i in range(x):
		id1 = random.randint(0,user_len-1)
		user = User.objects.all()[id1]
		title = '测试文章from: %s' %user
		body = post_generator()
		post = Post(user=user, title=title, body=body)
		post.save()
		print(post)

def add_comment(x):
	user_len = User.objects.all().count()
	post_len = Post.objects.all().count()
	for i in range(x):
		id1 = random.randint(0,user_len-1)
		id2 = random.randint(0,post_len-1)
		user = User.objects.all()[id1]
		post = Post.objects.all()[id2]
		body = comment_generator()
		comment = Comment(user=user, post=post, body=body)
		comment.save()
		print(comment)

post/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['category', 'title', 'body', 'price', 'origin_price']

	def __init__(self, *args, **kw):
		super(PostForm, self).__init__(*args, **kw)
		self.fields['title'].label = '标题'
		self.fields['body'].label = '正文'

class CommentForm(forms.Form):
	body = forms.CharField(label='商谈内容', max_length=100)
	

post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
from .models import Post, Comment, Category
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import random
# 写的真丑，有空改改

def index(request):
	"""主页面的视图"""
	if request.user.is_authenticated():
		username = request.user.username
		user = User.objects.get(username=username)
	# 选出浏览量最多的三个商品
	hot_post = Post.objects.all().order_by('-view_times')[0:3]
	categorys = Category.objects.all()

	# 每种商品选择三个浏览量最多的
	cate_post_list = []
	for i in categorys:
		cate_dict = {}		
		cate_post = Post.objects.filter(category=i).order_by('-view_times')[0:3]
		cate_dict['cate'] = i
		cate_dict['post'] = cate_post
		cate_post_list.append(cate_dict)
	return render(request, 'index.html', locals())

def category(request, cate_id):
	if request.user.is_authenticated():
		username = request.user.username
		user = User.objects.get(username=username)
	category = Category.objects.get(id=cate_id)
	cate_post = Post.objects.filter(category=category)
	return render(request, 'posts/category.html', locals())

@login_required(login_url='/transfer/')
def write(request):
	"""撰写文章的视图"""
	if request.user.is_authenticated():
		username = request.user.username
		user = User.objects.get(username=username)
		if request.method == 'POST':
			post = Post(user=user)
			post_form = PostForm(request.POST, instance=post)
			if post_form.is_valid():
				post_form.save()
				post.photo1 = request.FILES.get('photo1')
				post.photo2 = request.FILES.get('photo2')
				post.save()
				messages.info(request, '发布成功')
				return redirect('/')
			else:
				messages.info(request, '输入内容有误')
		else:
			post_form = PostForm()
			messages.get_messages(request)
			return render(request, 'posts/write.html', locals())

def posts(request, post_id):
	"""博客文章的详情页面,包括评论功能"""
	post = Post.objects.get(pk=post_id)
	post.view_times += 1
	post.save()
	if request.user.is_authenticated():   #登录了才有评论功能
		username = request.user.username
		user = User.objects.get(username=username)
		if request.method == 'POST':
			comment_form = CommentForm(request.POST)
			if comment_form.is_valid():
				comment = Comment(user=user, post=post, body=request.POST['body'])
				comment.save()
				messages.info(request, '评论已提交')
				return redirect('post:post', post_id=post.id)
			else:
				messages.info(request, '内容有问题')
		else:
			comment_form = CommentForm()

	comments_list = Comment.objects.filter(post=post).order_by('pub_date')
	paginator = Paginator(comments_list, 5)
	page = int(request.GET.get('page',1))
	try:
		comments = paginator.page(page)
	except PageNotAnInteger:
		comments = paginator.page(1)
	except EmptyPage:
		comments = paginator.page(paginator.num_pages)

	is_first_page = (page == 1)
	is_last_page = (page == paginator.num_pages)
	prev_page = (page - 1)
	next_page = (page + 1)
	total_page = paginator.num_pages

	messages.get_messages(request)
	return render(request, 'posts/post.html', locals())

def page_not_found(request):
	return render(request, '404.html')

def user_post(request,user_id):
	post_user = get_object_or_404(User, id=user_id)
	post_list = Post.objects.filter(user=post_user).order_by('-pub_date')
	paginator = Paginator(post_list, 5)
	page = int(request.GET.get('page',1))
	if request.user.is_authenticated():					# 目的是弄出右上角的个人选项，如果不用username的话，未登录的人在模板里的user是anonymous
		username = request.user.username
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	is_first_page = (page == 1)
	is_last_page = (page == paginator.num_pages)
	prev_page = (page - 1)
	next_page = (page + 1)
	total_page = paginator.num_pages

	return render(request, 'posts/all_posts.html', locals())

def user_comment(request,user_id):
	comment_user = get_object_or_404(User, id=user_id)
	comment_list = Comment.objects.filter(user=comment_user).order_by('-pub_date')
	paginator = Paginator(comment_list, 5)
	page = int(request.GET.get('page',1))
	if request.user.is_authenticated():
		username = request.user.username
	try:
		comments = paginator.page(page)
	except PageNotAnInteger: 
		comments = paginator.page(1)
	except EmptyPage:
		comments = paginator.page(paginator.num_pages)
	is_first_page = (page == 1)
	is_last_page = (page == paginator.num_pages)
	prev_page = (page - 1)
	next_page = (page + 1)
	total_page = paginator.num_pages

	return render(request, 'posts/all_comments.html', locals())

post/templates/posts/all_comments.html
{% extends "base.html" %}
{% block title %}Zlog - 评论{% endblock %}

{% block content %}
<div class="row clearfix">
	<div class="col-md-12 column">
		{% for comment in comments %}
		<div class="panel panel-success">
			<div class="panel-heading">
				<h3 class="panel-title">
					<div class="left">
						<a class="aa" href="{% url 'yonghu:profile' comment.user.id %}">
							<img class="post-head" src="{{comment.user.profile.head_cut.url}}">
						</a>
							{{ comment.user.profile.nickname }}
					</div>
					<div class="right">{{ comment.pub_date }}</div>
					<div class="row clearfix">
				</h3>
			</div>
			<div class="panel-body bg-post">
				{{ comment.body }}
				<p>{{ comment.user.post.count }}</p>

			</div>
			<div class="panel-footer">
				原文章: <a href="{% url 'post:post' comment.post.id %}">{{ comment.post.title }}</a>
			</div>
		</div>
		{% empty %}
		<div class="panel">
			<div class="panel-body">
				还没有想买的书耶...
			</div>
		</div>
		{% endfor %}
		<ul class="pagination">
			{% if not is_first_page %}
			<li><a href="?page=1">Top</a></li>
			<li><a href="?page={{prev_page}}">Prev</a></li>
			{% endif %}
			<li><a href="#">{{page}}</a></li>
			{% if not is_last_page %}
			<li><a href="?page={{next_page}}">Next</a></li>
			<li><a href="?page={{total_page}}">end</a></li>
			{% endif %}
		</ul>
	</div>
</div>
{% endblock %}

post/templates/posts/all_posts.html
{% extends "base.html" %}
{% block title %}Zlog - 文章{% endblock %}

{% block content %}
<div class="row clearfix">
	<div class="col-md-12 column">
		{% for post in posts %}
		<div class="panel panel-success">
			<div class="panel-heading">
				<h3 class="panel-title">
					<div class="left"><span>商品名：</span>
						<a class="aa" href="{% url 'post:post' post.id %}">{{ post.title }}</a>
					</div>
					<div class="right">
						<span>发布者：</span>
						<a class="aa" href="{% url 'yonghu:profile' post.user.id %}">
							<img class="post-head" src="{{post.user.profile.head_cut.url}}">
						</a>
							{{ post.user.profile.nickname }}
					</div>
					<div class="row clearfix">
				</h3>
			</div>
			<div class="panel-body bg-post">
				<span><font color="blue" size="4">商品描述：</font></span><br>{{ post.body }}<br>
			</div>
			<div class="panel-body bg-post">
				{% if post.photo1 %}
				<img class="img-rounded post-img" src="{{ post.photo1.url }}">
				{% endif %}
				{% if post.photo2 %}
				<img class="img-rounded post-img" src="{{ post.photo2.url }}">
				{% endif %}
				<br><br>
				<p>原价：￥{{post.origin_price}}</p>
				<p>售价：￥{{post.price}}</p>
			</div>
			<div class="panel-footer" >
				<div class="clearfix">
					<div class="pull-left">
						<span class="glyphicon glyphicon-eye-open"></span> 浏览量：{{post.view_times}}
					</div>
					<div class="pull-right">
						发布时间：{{post.pub_date}}
					</div>
				</div>
			</div>
		</div>
		{% empty %}
		<div class="panel">
			<div class="panel-body">
				还没有想分享的书耶...
			</div>
		</div>
		{% endfor %}
		<ul class="pagination">
			{% if not is_first_page %}
			<li><a href="?page=1">Top</a></li>
			<li><a href="?page={{prev_page}}">Prev</a></li>
			{% endif %}
			<li><a href="#">{{page}}</a></li>
			{% if not is_last_page %}
			<li><a href="?page={{next_page}}">Next</a></li>
			<li><a href="?page={{total_page}}">end</a></li>
			{% endif %}
		</ul>
	</div>
</div>
{% endblock %}

post/templates/posts/category.html
{% extends 'base.html' %}
{% block title %}old book - 分类{% endblock %}

{% block content %}
<h3>{{category.name}}</h3>
<div class="row clearfix">
{% for i in cate_post %}
<div class="panel panel-warning post-size">
	<div class="panel-heading">
		<h3 class="panel-title">
			<a href="{% url 'post:post' i.id %}">{{ i.title }}</a>
		</h3>
	</div>
	<div class="panel-body">
		{{ i.body | truncatechars:20 }}&nbsp;&nbsp;&nbsp;
		<a href="{% url 'post:post' i.id %}">详情>>></a>
		<div>
			<div class="panel-body">
				{% if i.photo1 %}
				<img class="img-rounded post-img" src="{{ i.photo1.url }}">
				{% endif %}
			</div>
			<p>原价：{{i.origin_price}}</p>
			<p>售价：{{i.price}}</p>
		</div>
	</div>
	<div class="panel-footer">
		<div class="clearfix">
			<div class="pull-left">
				<span class="glyphicon glyphicon-eye-open"></span> 浏览量：{{i.view_times}}
			</div>
			<div class="pull-right">
				发布时间：{{i.pub_date}}
			</div>
		</div>
	</div>
</div>
</div>
{% endfor %}
{% endblock %}

post/templates/posts/poll.html
{% extends "base.html" %}
{% block title %}Blogger - Write{% endblock %}

{% block content %}
	{% for message in messages %}
	<div class="alert">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
  		<strong>{{message.tags}}!</strong> {{ message }}
	</div>
	<script type="text/javascript">
		$(".alert").alert()
	</script>
	{% endfor %}


	<div class="row">
		<div class="panel panel-default">
			<div class="panel-header">
				<h3>{{ post.title }}</h3>
			</div>
			<div class="panel-body">
				<p>{{ post.body }}</p>
			</div>
			<div class="panel-footer">
				<p>作者:{{ post}}&nbsp;&nbsp;&nbsp;发布于:{{ post.pub_date }}</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="panel">
			<form action="." method='POST'>
				{% csrf_token %}
				<table>
					{{ comment_form.as_table }}
				</table>
				<input type="submit" value="发布">
			</form>
		</div>
	</div>
{% endblock %}

post/templates/posts/post.html
{% extends "base.html" %}
{% block title %}old book - 商品{% endblock %}

{% block content %}
<div class="row clearfix">
	<div class="col-md-12 column">
		<div class="panel panel-success">
			<div class="panel-heading">
				<h3 class="panel-title">
					<div class="left"><span>商品名：</span>{{ post.title }}</div>
					<div class="right">
						<span>发布者：</span>
						<a class="aa" href="{% url 'yonghu:profile' post.user.id %}">
							<img class="post-head" src="{{post.user.profile.head_cut.url}}">
						</a>
							{{ post.user.profile.nickname }}
					</div>
					<div class="row clearfix">
				</h3>
			</div>
			<div class="panel-body bg-post">
				<span><font color="blue" size="4">商品描述：</font></span><br>{{ post.body }}<br>
			</div>
			<div class="panel-body bg-post">
				{% if post.photo1 %}
				<img class="img-rounded post-img" src="{{ post.photo1.url }}">
				{% endif %}
				{% if post.photo2 %}
				<img class="img-rounded post-img" src="{{ post.photo2.url }}">
				{% endif %}
				<br><br>
				<p>原价：￥{{post.origin_price}}</p>
				<p>售价：￥{{post.price}}</p>
				<a href="{% url 'buy:add_to_buycar' post.id %}"><button class="btn btn-warning btn-mini">加入购物车</button></a>
				<a href="#"><button class="btn btn-danger btn-mini">立即购买</button></a>
			</div>
			<div class="panel-footer" >
				<div class="clearfix">
					<div class="pull-left">
						<span class="glyphicon glyphicon-eye-open"></span> 浏览量：{{post.view_times}}
					</div>
					<div class="pull-right">
						发布时间：{{post.pub_date}}
					</div>
				</div>
			</div>
		</div>

		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title">
					商谈
				</h3>
			</div>
			<div class="panel-body">
				{% if username %}
				<div class="content-form">
					<form action="." method="POST">
						{% csrf_token %}
					<!-- <input type="text" placeholder="Name" required/>
					<input type="text" placeholder="E-mail" required/>
					<input type="text" placeholder="Phone" required/>
					<textarea placeholder="Message"></textarea> -->
						{{ comment_form.as_table }}
						<input type="submit" value="提交"/>
					</form>
				</div>
				{% endif %}
			</div>
			<div class="panel-footer">
				<ul class="pagination">
					{% if not is_first_page %}
					<li><a href="?page=1">Top</a></li>
					<li><a href="?page={{prev_page}}">Prev</a></li>
					{% endif %}
					<li><a href="#">{{page}}</a></li>
					{% if not is_last_page %}
					<li><a href="?page={{next_page}}">Next</a></li>
					<li><a href="?page={{total_page}}">end</a></li>
					{% endif %}
				</ul>
				{% for comment in comments %}
				<div class="panel panel-success">
					<div class="panel-heading">
						<h3 class="panel-title">
							<div class="left">
								<a class="aa" href="{% url 'yonghu:profile' post.user.id %}">
									<img class="post-head" src="{{comment.user.profile.head_cut.url}}">
								</a>
									{{ comment.user.profile.nickname }}
							</div>
							<div class="right">{{ comment.pub_date }}</div>
							<div class="row clearfix">
						</h3>
					</div>
					<div class="panel-body bg-post">
						{{ comment.body }}
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

post/templates/posts/test.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>test</h1>
</body>
</html>

post/templates/posts/write.html
{% extends "base.html" %}
{% block title %}Zlog - 撰写{% endblock %}

{% block content %}
<div class="row clearfix">
	<div class="col-md-12 column">
		<form role="form" action="." method="POST" enctype='multipart/form-data'>
			{% csrf_token %}
			<div class="form-group">
				<label for="id_category">Category:</label> 
				<select id="id_category" name="category">
					<option value="" selected="selected">---------</option>
					<option value="1">文史类</option>
					<option value="2">武侠类</option>
					<option value="3">IT类</option>
					<option value="4">科普类</option>
					<option value="5">其他类</option>
				</select>
			</div>
			<div class="form-group">
				<label for="post_title">商品-标题</label>
				<input type="text" name="title" class="form-control" id="post_title" placeholder="这里输入标题...">
			</div>
			<div class="form-group">
				<label for="post_body">商品-详细</label>
				<textarea class="form-control" rows="3" id="post_body" name="body" placeholder="你想写点什么..."></textarea>
			</div>
			<div class="form-group">
				<label for="id_price">Price:</label> <input id="id_price" name="price" step="0.01" type="number" />
			</div>
			<div class="form-group">
				<label for="id_origin_price">Origin price:</label> <input id="id_origin_price" name="origin_price" step="0.01" type="number" />
			</div>
			<div class="form-group">
				<label for="post_photo1">图片1</label>
				<input type="file" id="post_photo1" name="photo1">
			</div>
			<div class="form-group">
				<label for="post_photo2">图片2</label>
				<input type="file" id="post_photo2" name="photo2">
			</div>

			
			<button type="submit" class="btn btn-default">发布</button>
		</form>
	</div>
</div>
{% endblock %}