book_shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from post.views import *
from yonghu.views import *
from backmanage.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', index, name='index'),
    url(r'^user/', include('yonghu.urls', namespace='yonghu')),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^transfer/$', login_required_transfer),
    url(r'^buy/', include('buy.urls', namespace='buy')),
    url(r'^manage/', include('backmanage.urls', namespace='manage')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buy/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
				url(r'^buycar/(?P<post_id>[0-9]+)/$', add_to_buycar, name="add_to_buycar"),
				url(r'^buycar/show/$', show_buycar, name="show_buycar"),
				url(r'^order/add/$', add_order, name="add_order"),
				url(r'^order/user_order/$', user_order, name='user_order'),
				url(r'^order/(?P<order_id>[0-9]+)/$', order, name='order'),
				url(r'^item/confirm/(?P<item_id>[0-9]+)/$', item_confirm, name="item_confirm"),
				url(r'^item/send/(?P<item_id>[0-9]+)/$', item_send, name="item_send"),
				url(r'^item/receive/(?P<item_id>[0-9]+)/$', item_receive, name="item_receive"),
			]

buy/models.py
from django.db import models
from django.contrib.auth.models import User
from post.models import Post

class Order(models.Model):
	buyer = models.ForeignKey(User, related_name='buyer', on_delete=models.DO_NOTHING)
	total = models.FloatField()
	address = models.CharField(max_length=50)
	generate_date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return "{0},date{1}".format(self.buyer, self.generate_date)

class OrderItem(models.Model):
	seller = models.ForeignKey(User, related_name='seller', on_delete=models.CASCADE)
	order = models.ForeignKey(Order, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	price = models.FloatField()
	status = models.IntegerField(default=0)

	# item状态 0:已提交, 1:已确认， 2：已发货, 3:已收货
	def confirm_item(self):
		self.status += 1
		self.save()
	def send_out_goods(self):
		self.status += 1
		self.save()
	def receive_goods(self):
		self.status += 1
		self.save()

	def __str__(self):
		return self.post.title

buy/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import *
from post.models import *


@login_required(login_url='/transfer/')
def add_to_buycar(request, post_id):
	if request.user.is_authenticated():
		username = request.user.username
		user = User.objects.get(username=username)
	# 拿到商品数据
	post = get_object_or_404(Post, id=post_id)
	buycar = request.session.get('buycar',None)
	if buycar == None:
		buycar = request.session['buycar'] = []
		print(buycar,123)
	buycar.append(post.id)
	request.session['buycar'] = buycar
	messages.info(request, '成功添加商品：{}'.format(post.title))
	return redirect('/')

@login_required(login_url='/transfer/')
def show_buycar(request):
	if request.user.is_authenticated():
		username = request.user.username
		user = User.objects.get(username=username)
	# 取出购物车内的商品id
	buycar = request.session['buycar']
	print('show',buycar)
	post_list = []
	total = 0
	for i in buycar:
		post = Post.objects.get(id=i)
		post_list.append(post)
		total += post.price

	return render(request, 'buy/buycar.html', locals())


@login_required(login_url='/transfer/')
def add_order(request):
	if request.user.is_authenticated():
		username = request.user.username
		user = User.objects.get(username=username)
		if request.method == 'POST':
			total = request.POST['total']
			address = request.POST['address']
			order = Order(buyer=user,total=total,address=address)
			order.save()
			# 订单的每个商品
			buycar = request.session['buycar']
			for i in buycar:
				post = Post.objects.get(id=i)
				item = OrderItem(order=order, seller=post.user, post=post, price=post.price)
				item.save()
			messages.info(request, '订单创建成功！')
			return redirect('index')



@login_required(login_url='/transfer/')
def user_order(request):
	if request.user.is_authenticated():
		username = request.user.username
		user = User.objects.get(username=username)
		# 获取用户提交的的订单
		orders = Order.objects.filter(buyer=user)
		order_list = []
		for i in orders:
			x = {}
			x['order'] = i
			x['items'] = i.orderitem_set.all()
			order_list.append(x)

		# 获取用户被下单的商品
		items = OrderItem.objects.filter(seller=user)
		print(items)
		return render(request, 'buy/user_order.html', locals())

def order(request, order_id):
	if request.user.is_authenticated():
		username = request.user.username
		user = User.objects.get(username=username)
	order = Order.objects.get(id=order_id)
	items = OrderItem.objects.filter(order=order)
	return render(request, 'buy/order.html', locals())

def item_confirm(request, item_id):
	item = OrderItem.objects.get(id=item_id)
	item.confirm_item()
	return redirect('buy:user_order')

def item_send(request, item_id):
	item = OrderItem.objects.get(id=item_id)
	item.send_out_goods()
	return redirect('buy:user_order')

def item_receive(request, item_id):
	item = OrderItem.objects.get(id=item_id)
	item.receive_goods()
	return redirect('buy:user_order')

buy/templates/buy/buycar.html
{% extends "base.html" %}
{% block title %}old book - 购物车{% endblock %}

{% block content %}
<div class="row clearfix">
	<div class="col-md-12 column">
		<table class="table table-hover table-striped">
			<thead>
				<tr>
					<th>
						商品编号
					</th>
					<th>
						商品名称
					</th>
					<th>
						商品价格
					</th>
					<th>
						发布时间
					</th>
				</tr>
			</thead>
			<tbody>
				{% for post in post_list %}
				<tr class="{% cycle '' 'success' 'error' 'warning' 'info' %}">
					<td>
						{{ post.id }}
					</td>
					<td>
						{{ post.title | truncatechars:10 }}
					</td>
					<td>
						{{ post.price }}
					</td>
					<td>
						{{ post.pub_date }}
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<p class="bg-success">总价：{{ total }}</p>
		
		<div class="row clearfix">
			<div class="col-md-12 column">
				<form role="form" action="{% url 'buy:add_order' %}" method="POST">
					{% csrf_token %}
					<div class="form-group">
						 <label for="exampleInputAddress">收货地址</label>
						 <input type="text" name="address" class="form-control" id="exampleInputAddress" />
						 <input type="hidden" name="total" value="{{total}}">
					</div>
					 <button type="submit" class="btn btn-default">提交订单</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

buy/templates/buy/order.html
{% extends "base.html" %}
{% block title %}old book - 订单{% endblock %}

{% block content %}
<div class="row clearfix">
	<div class="col-md-12 column">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					买家：{{order.order.buyer}}&nbsp;&nbsp;&nbsp;
					下单时间：{{order.order.generate_date}}
				</h3>
			</div>
			<div class="panel-body">
				<table class="table">
					<thead>
						<tr>
							<th>
								卖家
							</th>
							<th>
								商品
							</th>
							<th>
								价格
							</th>
							<th>
								状态
							</th>
							<th>
							</th>
						</tr>
					</thead>
					<tbody>
						{% for item in order.items %}
						<tr>
							<td>
								{{item.seller}}
							</td>
							<td>
								{{item.post.title}}
							</td>
							<td>
								{{item.price}}
							</td>
							<td>
								{% if item.status == 0 %}
									已提交
								{% elif item.status == 1 %}
									已确认
								{% elif item.status == 2 %}
									已发货
								{% elif item.status == 3 %}
									已完成
								{% else %}
									None
								{% endif %}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<div class="panel-footer">
				<p>收货地址：{{order.address}}</p>
				<p>总价：{{order.total}}</p>
				<p>下单时间：{{order.generate_date}}</p>
			</div>
		</div>
	</div>
</div>
{% endblock %}

buy/templates/buy/user_order.html
{% extends "base.html" %}
{% block title %}old book - 用户订单{% endblock %}

{% block content %}
<div class="row clearfix">
	<div class="col-md-12 column">
		{% for order in order_list %}
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					买家：<font color="blue">{{order.order.buyer}}</font>&nbsp;&nbsp;&nbsp;
					
				</h3>
			</div>
			<div class="panel-body">
				<table class="table">
					<thead>
						<tr>
							<th>
								卖家
							</th>
							<th>
								商品
							</th>
							<th>
								价格
							</th>
							<th>
								状态
							</th>
							<th>
							</th>
						</tr>
					</thead>
					<tbody>
						{% for item in order.items %}
						<tr>
							<td>
								{{item.seller}}
							</td>
							<td>
								{{item.post.title}}
							</td>
							<td>
								{{item.price}}
							</td>
							<td>
								{% if item.status == 0 %}
									已提交
								{% elif item.status == 1 %}
									已确认
								{% elif item.status == 2 %}
									已发货
									<a href="{% url 'buy:item_receive' item.id %}"><button class="btn">确认收货</button></a>
								{% elif item.status == 3 %}
									已完成
								{% else %}
									None
								{% endif %}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<div class="panel-footer">
				<p>收货地址：<font color="blue">{{order.order.address}}</font></p>
				<p>总价：<font color="blue">{{order.order.total}}</font></p>
				<p>下单时间：<font color="blue">{{order.order.generate_date}}</font></p>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
<div class="row clearfix">
	<div class="col-md-12 column">
		{% for item in items %}
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					商品名：{{item.post.title}}
				</h3>
			</div>
			<div class="panel-body">
				<p>订单号：{{item.order.id}}</p>
				<p>买家：{{item.order.buyer}}</p>
				<p>价格：{{item.price}}</p>
				<p>
					状态：
					{% if item.status == 0 %}
						已提交
					{% elif item.status == 1 %}
						已确认
					{% elif item.status == 2 %}
						已发货
					{% elif item.status == 3 %}
						已完成
					{% else %}
						None
					{% endif %}
				</p>
				{% if item.status == 0 %}
					<a href="{% url 'buy:item_confirm' item.id %}"><button class="btn">确认订单</button></a>
				{% elif item.status == 1 %}
					<a href="{% url 'buy:item_send' item.id %}"><button class="btn">已经发货</button></a>
				{% endif %}
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}