book_shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from post.views import *
from yonghu.views import *
from backmanage.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', index, name='index'),
    url(r'^user/', include('yonghu.urls', namespace='yonghu')),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^transfer/$', login_required_transfer),
    url(r'^buy/', include('buy.urls', namespace='buy')),
    url(r'^manage/', include('backmanage.urls', namespace='manage')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buy/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
				url(r'^buycar/(?P<post_id>[0-9]+)/$', add_to_buycar, name="add_to_buycar"),
				url(r'^buycar/show/$', show_buycar, name="show_buycar"),
				url(r'^order/add/$', add_order, name="add_order"),
				url(r'^order/user_order/$', user_order, name='user_order'),
				url(r'^order/(?P<order_id>[0-9]+)/$', order, name='order'),
				url(r'^item/confirm/(?P<item_id>[0-9]+)/$', item_confirm, name="item_confirm"),
				url(r'^item/send/(?P<item_id>[0-9]+)/$', item_send, name="item_send"),
				url(r'^item/receive/(?P<item_id>[0-9]+)/$', item_receive, name="item_receive"),
			]

post/urls.py
from django.conf.urls import url
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^write/', write, name='write'),
	url(r'^post/(?P<post_id>[0-9]+)/$', posts, name='post'),
	url(r'^userpost/(?P<user_id>[0-9]+)/$', user_post, name='user_post'),
	url(r'^usercomment/(?P<user_id>[0-9]+)/$', user_comment, name='user_comment'),
	url(r'category/(?P<cate_id>[0-9]+)/$', category, name='category'),
]

yonghu/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^profile/(?P<user_id>[0-9]+)/$', profile, name="profile"),
	url(r'^login/', login, name='login'),
	url(r'^logout/', logout, name='logout'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	{% load staticfiles %}
	<!-- <link rel="shortcut icon" href="{% static 'favicon.ico' %}" /> -->
	<link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
				<div class="navbar-header">
					 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="{% url 'index' %}">old book</a>
				</div>
				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active">
							 <a href="{% url 'index' %}">主页</a>
						</li>
						<li>
							 <a href="{% url 'post:write' %}">发布</a>
						</li>
						
					</ul>
					<form class="navbar-form navbar-left" role="search">
						<div class="form-group">
							<input type="text" class="form-control" />
						</div> <button type="submit" class="btn btn-default">Submit</button>
					</form>
					<ul class="nav navbar-nav navbar-right">

						{% if username %}
							<li><a href="{% url 'buy:show_buycar' %}"><span class="glyphicon glyphicon-shopping-cart"></span> 购物车</a></li>
							<li><a href="{% url 'buy:user_order' %}"><span class="glyphicon glyphicon-shopping-cart"></span> 订单</a></li>
							<li class="dropdown">
								 <a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<img class="img-thumbnail post-head" src="{{user.profile.head_cut.url}}">
									{{ user.profile.nickname }}
									<strong class="caret"></strong>
								</a>
								<ul class="dropdown-menu">
									<li><a href="{% url 'yonghu:profile' user.id %}">资料</a></li>
									<li><a href="{% url 'post:user_post' user.id %}">我发布的</a></li>
									<li><a href="#">change password(未做)</a></li>
									<li class="divider"></li>
									<li><a href="{% url 'yonghu:logout' %}">注销</a></li>
								</ul>
							</li>
						{% else %}
							<li><a href="/accounts/register">注册</a></li>
							<li><a href="{% url 'yonghu:login' %}">登录</a></li>
						{% endif %}
						
						<li>&nbsp;&nbsp;</li>
					</ul>
				</div>
				
			</nav>
		</div>
	</div>
<br><br><br><br>
	<div class="row clearfix">
		<div class="col-md-12 column">
			{% for message in messages %}
			<div class="alert alert-dismissable alert-info">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
				<strong>{{message.tags}}!</strong> {{ message }}
			</div>
			{% endfor %}

			{% block head %}
			{% endblock %}
		</div>
	</div>
	<!-- banner end -->
	<div class="row clearfix">
		{% block content %}
		{% endblock %}
	</div>
	<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="page-header">
				<h1>
					个人学习制作 <small>邮箱：1019437875@qq.com</small>
				</h1>
			</div>
		</div>
	</div>
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}old book{% endblock %}

{% block head %}
<div class="jumbotron">
	<h2>
		你好，朋友！
	</h2>
	<p>
		在这里你可以随意浏览其他人发布的书籍，挑选几本你喜欢的购买吧！ <br>
		或者把你喜欢的书发布出来，分享给大家。
	</p>
	<p>
		 <a class="btn btn-primary btn-large" href="#">Learn more</a>
	</p>
</div>
{% endblock %}

{% block content %}
	<div class="row clearfix">
		{% for hot in hot_post %}
		<div class="col-md-4 column">
			<div class="panel panel-warning">
				<div class="panel-heading">
					<h3 class="panel-title">
						<a href="{% url 'post:post' hot.id %}">{{ hot.title }}</a>
					</h3>
				</div>
				<div class="panel-body">
					{{ hot.body | truncatechars:20 }}&nbsp;&nbsp;&nbsp;
					<a href="{% url 'post:post' hot.id %}">详情>>></a>
					<div>
						<div class="panel-body">
							{% if hot.photo1 %}
							<img class="img-rounded post-img" src="{{ hot.photo1.url }}">
							{% endif %}
						</div>
						<p>原价：{{hot.origin_price}}</p>
						<p>售价：{{hot.price}}</p>
					</div>
				</div>
				<div class="panel-footer">
					<div class="clearfix">
						<div class="pull-left">
							<span class="glyphicon glyphicon-eye-open"></span> 浏览量：{{hot.view_times}}
						</div>
						<div class="pull-right">
							发布时间：{{hot.pub_date}}
						</div>
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>

	{% for i in cate_post_list %}
	<div class="raw clearfix">
		<h2>
			{{i.cate.name}}
			<a href="{% url 'post:category' i.cate.id %}">
				<button class="btn btn-primary btn-mini">查看更多>>></button>
			</a>
		</h2>
		
		
		{% for j in i.post %}
		<div class="col-md-4 column">
			<div class="panel panel-warning">
				<div class="panel-heading">
					<h3 class="panel-title">
						<a href="{% url 'post:post' j.id %}">{{ j.title }}</a>
					</h3>
				</div>
				<div class="panel-body">
					{{ j.body | truncatechars:20 }}&nbsp;&nbsp;
					<a href="{% url 'post:post' j.id %}">详情>>></a>
					<div>
						<div class="panel-body">
							{% if j.photo1 %}
							<img class="img-rounded post-img" src="{{ j.photo1.url }}">
							{% endif %}
						</div>
						<p>原价：{{j.origin_price}}</p>
						<p>售价：{{j.price}}</p>
					</div>
				</div>
				<div class="panel-footer">
					<div class="clearfix">
						<div class="pull-left">
							<span class="glyphicon glyphicon-eye-open"></span> 浏览量：{{j.view_times}}
						</div>
						<div class="pull-right">
							发布时间：{{j.pub_date}}
						</div>
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
	{% endfor %}
{% endblock %}